=== vitoss-ux/HTML-CSS-XML/HTML_CSS_XML/XML/Работа с DTD схемами/library.dtd
<!ELEMENT library (book_catalog, author_catalog)>

<!ELEMENT book_catalog (book*)>
<!ELEMENT book (authors?, title, publishing, annotation?)>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT publishing (#PCDATA)>
<!ELEMENT annotation (#PCDATA)>

<!ELEMENT author_catalog (author_book*)>
<!ELEMENT author_book (#PCDATA)>

<!ATTLIST book 
	id ID #REQUIRED
	isbn CDATA #IMPLIED
	year CDATA #REQUIRED 
	issue (translation | original) "translation">  

	<!ATTLIST author_book  idref IDREF #REQUIRED>

<!ENTITY linux "Linux">
<!ENTITY internet "Internet">

=== vitoss-ux/HTML-CSS-XML/HTML_CSS_XML/XML/Работа с DTD схемами/library.xml
<?xml version = "1.0" encoding = "utf-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
	<book_catalog>
		<book id = "ID" isbn = " " year = " " issue = "translate">
			<authors>
				<author></author>
			</authors>
			<title></title>
			<publishing></publishing>
			<annotation></annotation>
		</book>
	</book_catalog>
	<author_catalog>
		<author_book idref = " "/>
	</author_catalog>
</library>
